# список пользователей всех
GET http://localhost:5000/users/
Content-Type: application/json

###

# список пользователей по id
GET http://localhost:5000/users/2
Content-Type: application/json

###

# создание юзера
POST http://localhost:5000/users/
Content-Type: application/json

{
  "username": "test43",
  "email": "t34@mail.ru",
  "password": "sss"
}

###

# удаление юзера
DELETE http://localhost:5000/users/3
Content-Type: application/json

###

# список всех объявлений
GET http://localhost:5000/ads/
Content-Type: application/json

###

# создание объявления
POST http://localhost:5000/ads/
Content-Type: application/json

{
  "title": "Куплю утюг",
  "description": "ну продайте кто-нибудь утюг блин",
  "user_id": 55
}

###