# список пользователей всех
GET http://localhost:5000/users/
Content-Type: application/json
Authorization: Basic testuser 123

###

# список пользователей по id
GET http://localhost:5000/users/2
Content-Type: application/json

###

# создание юзера
POST http://localhost:5000/users/
Content-Type: application/json

{
  "username": "testuser",
  "email": "ttt@mail.ru",
  "password": "123"
}

###

# удаление юзера
DELETE http://localhost:5000/users/10
Content-Type: application/json
Authorization: Basic testuser 123

###

# список всех объявлений
GET http://localhost:5000/ads/
Content-Type: application/json

###

# создание объявления
POST http://localhost:5000/ads/
Content-Type: application/json
Authorization: Basic testuser 123

{
  "title": "Карты деньги 2 ствола",
  "description": "ШОООО",
  "user_id": 11
}

###

# обновление объявления
PATCH http://localhost:5000/ads/3
Content-Type: application/json
Authorization: Basic testuser 123

{
  "title": "УДАЛЕНО",
  "description": "Спасибо купил"
}

###

# удаление объявления
DELETE http://localhost:5000/ads/1
Content-Type: application/json
Authorization: Basic testuser 123

###

# обновление объявления, чисто пользователя, нельзя так
PATCH http://localhost:5000/ads/3
Content-Type: application/json
Authorization: Basic testuser 123

{
  "user_id": 1
}

###
