"""len changed for password

Revision ID: 968e5d28c36f
Revises: df206202f839
Create Date: 2021-09-03 13:56:00.304712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968e5d28c36f'
down_revision = 'df206202f839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
